name: 🚀 Deploy via FTP

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: 🎉 Deploy to alwaysData
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files to alwaysData FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.alwaysdata.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public/
